openapi: 3.0.1
info:
  title: defaultTitle
  description: defaultDescription
  version: '0.1'
servers:
  - url: 'http://localhost:5000'
paths:
  /api/ingestmetadata:
    post:
      description: API Endpoint to ingest metadata json blob files, based on source and type
      requestBody:
        content:
          application/json:
            schema:
              type: array
              properties:
                blobs:
                  type: array
      responses:
        '200':
          description: Successfully Ingested JSON metadata
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://localhost:5000'
    servers:
      - url: 'http://localhost:5000'
  /api/querymetadata:
    get:
      description: API Endpoint to Query Metadata based on multiple filters
      responses:
        '200':
          description: Metadata successfully queried
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://localhost:5000'
    servers:
      - url: 'http://localhost:5000'
  /:
    get:
      description: Auto generated using Swagger Inspector
      responses:
        '200':
          description: Auto generated using Swagger Inspector
          content:
            text/html; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://localhost:5000'
    servers:
      - url: 'http://localhost:5000'
